DROP TABLE IF EXISTS Genres CASCADE;
DROP TABLE IF EXISTS MPA CASCADE;
DROP TABLE IF EXISTS Films CASCADE;
DROP TABLE IF EXISTS Users CASCADE;
DROP TABLE IF EXISTS Friends CASCADE;
DROP TABLE IF EXISTS Likes CASCADE;
DROP TABLE IF EXISTS filmGenres CASCADE;

CREATE TABLE IF NOT EXISTS Genres (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);


CREATE TABLE IF NOT EXISTS MPA (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(255) NOT NULL
);


CREATE TABLE IF NOT EXISTS Films (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar NOT NULL,
  description varchar(200),
  releaseDate date,
  duration integer,
  MPA integer,
  FOREIGN KEY (MPA) REFERENCES MPA(id)
);


CREATE TABLE IF NOT EXISTS Users (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email varchar(255) NOT NULL UNIQUE,
  login varchar(255) NOT NULL UNIQUE,
  name varchar(255) NOT NULL,
  birthday date NOT NULL
);

CREATE TABLE IF NOT EXISTS Friends (
  userId integer,
  friendId integer,
  status integer NOT NULL,
  PRIMARY KEY (userId, friendId),
  FOREIGN KEY (userId) REFERENCES Users(id),
  FOREIGN KEY (friendId) REFERENCES Users(id)
);

CREATE TABLE IF NOT EXISTS Likes (
  userId integer,
  filmId integer,
  PRIMARY KEY (userId, filmId),
  FOREIGN KEY (userId) REFERENCES Users(id),
  FOREIGN KEY (filmId) REFERENCES Films(id)
);

CREATE TABLE IF NOT EXISTS FilmGenres (
  filmId INTEGER,
  genreId INTEGER,
  FOREIGN KEY (filmId) REFERENCES Films(id),
  FOREIGN KEY (genreId) REFERENCES Genres(id),
  PRIMARY KEY (filmId, genreId)
);
