DROP TABLE IF EXISTS filmGenres CASCADE;
DROP TABLE IF EXISTS MPA CASCADE;
DROP TABLE IF EXISTS films CASCADE;
DROP TABLE IF EXISTS friendStatus CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS userFriends CASCADE;
DROP TABLE IF EXISTS usersFilms CASCADE;
DROP TABLE IF EXISTS filmGenre CASCADE;

CREATE TABLE IF NOT EXISTS filmGenres (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255)
);


CREATE TABLE IF NOT EXISTS MPA (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(255)
);


CREATE TABLE IF NOT EXISTS films (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar NOT NULL,
  description varchar(200),
  releaseDate date,
  duration integer,
  MPA integer,
  FOREIGN KEY (MPA) REFERENCES MPA(id)
);

CREATE TABLE IF NOT EXISTS friendStatus (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  status varchar(255)
);


CREATE TABLE IF NOT EXISTS users (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email varchar(255) NOT NULL,
  login varchar(255) NOT NULL,
  name varchar(255) NOT NULL,
  birthday date NOT NULL
);

CREATE TABLE IF NOT EXISTS userFriends (
  userId integer,
  friendId integer,
  status integer NOT NULL,
  PRIMARY KEY (userId, friendId),
  FOREIGN KEY (status) REFERENCES friendStatus(id),
  FOREIGN KEY (userId) REFERENCES users(id),
  FOREIGN KEY (friendId) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS usersFilms (
  userId integer,
  filmId integer,
  PRIMARY KEY (userId, filmId),
  FOREIGN KEY (userId) REFERENCES users(id),
  FOREIGN KEY (filmId) REFERENCES films(id)
);

CREATE TABLE IF NOT EXISTS filmGenre (
  filmId INTEGER,
  genreId INTEGER,
  FOREIGN KEY (filmId) REFERENCES films(id),
  FOREIGN KEY (genreId) REFERENCES filmGenres(id),
  PRIMARY KEY (filmId, genreId)
);
